### ISSUE TITLE
Add ARM64 version of library compatible with Invidious

### ISSUE THREAD

**Issue by DUOLabs333** [omarroth/lsquic.cr#14]
I tried compiling an ARM64 version of liblsquic, but when I went to compile it into Invidious, it failed because of missing references (research tells me this is because my OpenSSL is too recent.

**Comment by unixfox** [comment]
You are using Docker right? Then you can use our ARM64 docker image: https://github.com/iv-org/invidious/issues/361#issuecomment-881047911

And we have a ARM64 docker image for lsquic too: https://quay.io/repository/invidious/lsquic-compiled?tab=tags

**Comment by DUOLabs333** [comment]
I was hoping to do it without Docker, but I guess that's the best available.

**Comment by DUOLabs333** [comment]
I'm now trying to build this again in a proper build environment, but I don't want to have to download a separate image just to extract a library.

**Comment by unixfox** [comment]
If you are using alpine linux you can build boringssl and lsquic directly without docker:
- https://github.com/iv-org/lsquic.cr/blob/master/docker/APKBUILD-lsquic
- https://github.com/iv-org/lsquic.cr/blob/master/docker/APKBUILD-boringssl

By the way, we recently don't require to use lsquic anymore. One can build without lsquic/quic with `crystal build -Ddisable_quic invidious/invidious.cr` and this will use the built-in HTTP client from crystal.

**Comment by DUOLabs333** [comment]
> By the way, we recently don't require to use lsquic anymore.

Neat.
